

CONFIG_UBOOT_NAME = "uboot"
CONFIG_NVRO_NAME = "NV_RO"
CONFIG_NVRW_NAME = "NV_RW"
CONFIG_KERNEL_NAME = "kernel"
CONFIG_UPDATEFS_NAME = "updatefs"
CONFIG_USERFS_NAME = "userfs"
CONFIG_PUBLIC_KEYS = res/testkey.x509.pem
CONFIG_PRIVATE_KEYS = res/testkey.pk8
CONFIG_BLOCKSIZE=32*1024
