#!/bin/sh
#
# Start adb....
#

case "$1" in
  start)
	echo "watchdog start..."
	/etc/init.d/watchdogd.sh &
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
